import type { PropertyCardProps } from "@/components/property/property-card";

export const DEMO_PROPERTIES: PropertyCardProps[] = [
  {
    id: "1",
    slug: "modern-2br-downtown-loft",
    title: "Modern 2BR Downtown Loft",
    price: 2500,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1100,
    city: "Austin",
    state: "TX",
    propertyType: "APARTMENT",
    primaryImage: {
      url: "https://placehold.co/800x600/f59e0b/ffffff?text=Modern+Loft",
      alt: "Modern Downtown Loft",
    },
  },
  {
    id: "2",
    slug: "cozy-1br-capitol-hill",
    title: "Cozy 1BR on Capitol Hill",
    price: 1200,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 650,
    city: "Denver",
    state: "CO",
    propertyType: "STUDIO",
    primaryImage: {
      url: "https://placehold.co/800x600/d97706/ffffff?text=Capitol+Hill+Studio",
      alt: "Cozy Capitol Hill Studio",
    },
  },
  {
    id: "3",
    slug: "spacious-3br-pearl-district",
    title: "Spacious 3BR in Pearl District",
    price: 3200,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1450,
    city: "Portland",
    state: "OR",
    propertyType: "CONDO",
    primaryImage: {
      url: "https://placehold.co/800x600/b45309/ffffff?text=Pearl+District+Condo",
      alt: "Pearl District Condo",
    },
  },
  {
    id: "4",
    slug: "charming-2br-fremont-cottage",
    title: "Charming 2BR Fremont Cottage",
    price: 2800,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 950,
    city: "Seattle",
    state: "WA",
    propertyType: "HOUSE",
    primaryImage: {
      url: "https://placehold.co/800x600/92400e/ffffff?text=Fremont+Cottage",
      alt: "Charming Fremont Cottage",
    },
  },
  {
    id: "5",
    slug: "luxury-2br-midtown-highrise",
    title: "Luxury 2BR Midtown Highrise",
    price: 3500,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1300,
    city: "Sacramento",
    state: "CA",
    propertyType: "APARTMENT",
    primaryImage: {
      url: "https://placehold.co/800x600/78350f/ffffff?text=Midtown+Highrise",
      alt: "Luxury Midtown Highrise",
    },
  },
  {
    id: "6",
    slug: "sunny-1br-south-congress",
    title: "Sunny 1BR near South Congress",
    price: 1450,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 720,
    city: "Austin",
    state: "TX",
    propertyType: "APARTMENT",
    primaryImage: {
      url: "https://placehold.co/800x600/fbbf24/ffffff?text=South+Congress+Apt",
      alt: "Sunny South Congress Apartment",
    },
  },
];
